#!/usr/bin/env bash
set -euo pipefail
PAGES=("about" "alerts" "announcements" "booking" "bookings" "contact" "departures" "events" "faqs" "ferry" "home" "login" "maps" "parks" "permits" "programs" "routes" "schedule" "search" "status" "support" "tickets" "terminals" "fares" "privacy" "terms" "accessibility" "sitemap" "arrivals" "help" "news" "notices" "reports" "notifications" "language" "profile" "saved-routes" "ticket-history" "service-areas" "island-access" "peak-hours" "travel-tips" "system-health" "audit-logs" "cms" "admin" "dashboard" "content" "users" "settings" "logs")
for page in "${PAGES[@]}"; do
  dir="src/app/(site)/$page"
  mkdir -p "$dir"
  cat > "$dir/page.tsx" <<EOT
import type { Metadata } from "next";
export const metadata: Metadata = { title: "${page^}", description: "Expanded content page for ${page}." };
export default function Page() {
  return <section className="container-pfr py-12"><div className="card p-8"><h1 className="text-3xl font-bold">${page^}</h1><p className="mt-3 text-white/70">This route is generated by the bulk page generator and ready for real content.</p></div></section>;
}
EOT
done
